version: "3"

services:
  php-server:
    image: php:apache
    restart: always
    ports:
      - 3001:80
    volumes:
      - ./:/var/www/html

  mysql-server:
    image: mysql:8.3.0-oracle
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}